baseURL: http://example.org/
languageCode: en-us
title: Nicolas Chan
theme: "PaperMod"

enableRobotsTXT: true

minify:
  disableXML: true
  minifyOutput: true

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  hideFooter: true
  defaultTheme: auto
  math: true
  showCodeCopyButtons: true
  showtoc: true
  showRssButtonInSectionTermList: true
  umami: true
  homeInfoParams:
    Title: "Nicolas Chan's Blog"
    Content: >
      - Software engineering and anything else on my mind &#x1F301;
  socialIcons:
    - name: GitHub
      url: "https://github.com/nicolaschan"
    - name: Keybase
      url: "https://keybase.io/nicolaschan"
    - name: CV 
      url: "/static/docs/resume-2022.pdf"
    - name: RSS
      url: "/index.xml"

  editPost:
    URL: "https://github.com/nicolaschan/blog/tree/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

menu:
  main:
    - identifier: about
      name: About Me
      url: /about/
      weight: 10
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30